version: '3.1'

volumes:
  postgres_vol:

networks:
  postgress_net:
    driver: bridge

services:
  api:
    image: dpage/pgadmin4:latest
    build: 
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 8080:80
    networks:
      - postgress_net
    environment:
      PGADMIN_DEFAULT_EMAIL: 'wellington.ts@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: pgpwd
    
  postgresdb:
    image: postgres:15
    ports:
      - 5432:5432
    networks:
      - postgress_net
    volumes:
      - postgres_vol:/data/db
    environment:
      POSTGRES_PASSWORD: postpwd
      POSTGRES_USER: postuser
      POSTGRES_DB: postdb